name: sendgrid
description: "Production Instance of Sendgrid"
type: subscription
locations:
  - name: api
    url: "https://api.sendgrid.com"

descriptors:
    default: 0.0.1
    supported:
        - version: 0.0.1
          url: "file://$ARIGATO_INSTALL/descriptors/sendgrid/service.yml"
