name: twilio
description: "Production Instance of Twilio"
type: subscription
locations:
  - name: api
    url: "https://api.twilio.com"

descriptors:
    default: 0.0.1
    supported:
        - version: 0.0.1
          src: "../../descriptors/twilio/service.yml"
