sudo: required
branches:
  only:
  - master
language: bash
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get -o Dpkg::Options::="--force-confnew" install -y --force-yes docker-engine
cache:
  apt: true
  directories:
  - vendor
script:
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- make container
- make docker-test
env:
  global:
  - secure: mhoHIPRY5bdwXVFy0SODWFBmcFuv6ORmQU+8xsMjajdqcJL3FfFlhlzixsrjqJQs9l0lwjlsSRgFj/Oer1JWuMDAOhvuJ5nGcUY2abfj7PC+Y9we/rofxKz7lNNMPtTctRaidlbOsAGQdfNJeVAOzGF7lRL+NGQarWotSEVKTVWajWUPCVC6lvJNu4qYE88onSU1xqL8mSJaKr+mp5hSc6y//fjKNlwzF2jziB+t1WLXYq1+OwA5sP+pNtCOo1lEopHJrEwMT0Gucbkf6pWNzeDg8c3sB1hsBB9ApTtjBLka/eWv5JtHRGFJdm+GeicDcLjCIL1a+zaGiB+1dfiHqzy/rnet2tIt26MmB7+Mnhq7khN4TVhNnEdImDnwIXI5sEfpOZl+hmGaUlyTkxbHQLwl0I7gOpCxJKLUcDj2fG9ZcWtN4OZFilhjtmOi5LxQAwURiHSGMcH28h/yCMzn9ralgXnEjxLd3R6P5nFkHGU08fLnERMYMOkw/KtHYevVuTB/E8R62IRMORRqEf27wrFK+LtArW+ZhNSVeyNlJMt+SoOaCSLWdnRpF3Q1ZEiRHNkmreo/662kSM/LGX9v+RYorHq8y07p8oIgfN9ybkPvgVZREmD5IBQL/ZQbQktvYtG4Ev3TIFkJZ08eluN+kdwPusjSxjvLuW7W9+rkQjg=
  - secure: h36q+0zZ5XkAsG8TBYzUQny9rsy5X5TfMClFq0XWq1Pez6XY4ISwizjiSkHdEg2A4w5+gbvAMCtOqNvc8MfSV3hKM6bWCz9FWeEuQzCo0Ae6ff+k78r9uOe4CklgPJGcCteFqjqGedRzYn8fMgW3wD1laipBuSTjdG9uipsLzY0g2NFejIevf1b5JHk/25rNK1g/gq+ZWRR/L5LGf+azq+6OD1/02FkcC6+WeOIxXySI/QDsOg2DOWO/h2CS/5O94mLMqVCZ2hXakmeI9gWAfKTzGrTxs0KTg81iVOq+W4rxcWQCAScs9Uq3AFvuovprLQP8ozH+xSkADexLPTUg9dzanU2XroPVEAaqP0jxs+J0odZWDgwoMC7+/ktUsom9Ld9Ck5Wv7QwXYspOLUyetf4NXC7EF0hMGOXM8jvXQUDx3qqPKaHk5pVLdaqo29Wj9f4yWWYzzHUR9LvOpi/DkqXOanbIJEbNjIzfgUUxSeUcqe1hlMq5pe1xxC8DywNOy/LhuKxZwKiS785LOiokj+C9O9beYsNUJUW5qhPdDMpTYXmc/rWYFVRGQ02Xz2GFVQhzhvkIKi5NnzWr6mDa0n5XWjWeuJ2Yjx3VK99zV5l2xIWPV34kFhrLQpUm40CDbgcaF1e2a5hNhfxU2Jc7fbripq+YgaXmULBqBSm0NDw=
notifications:
  slack:
    secure: tVqhEylsmLVEJD8U/Yot0wcvVxLdka7YFIKv4s4UuHc0fWvMsEL+KURnLlfEod9+0rwVAy7j9jqmFQiyq2MzIL/aEmGP23+mEnFQbrpqxY+4wu5MYLNIa8BXWoFrZPxndLjVyIWsps4oJi01fs8cYnFkvCI999ABBU2Pq5etqAg6Vcw4SdR772j0cIe+dipZr+7YuIiArxCq5kjBKhs1cF0py1PyJLLV2n4yED5DmOe/1f1ZnprH9hAYur2a0oYZfV3wNqOpROTJzYdArQro+XpUuhrqH+TmZDNvdYHZMKNqryRRrJF764k/yQ3AjZJu4/GQp8Tm4khwX+6NSDJzEi6xboeeP/4Gl+PW5v2hkNWQR+LU/GmtJj1WuaIBRC02EbTcOjSTINYRA+BXK5ZvovW6H8WBsOu60KC21OhrcUmq/FqBbaXKuiFjjX3giStf7wQhV9bsBoflANETvZ0uYVPJnuT6568L+qcNVCUtqVWluMs895m00bsAmho6NZNIElBuBL0ZM81QwVRLxpb1J9DxSXrVaVrLsMEK9+o9SPuAV/BuktnpyZk1MZ4ufwLkSCqQxn4bTcpjQJSVIXBRdz7Hh2NhEAKbinNnECx1RAeu4S7SopP0IbfT53+JRojSA2i4up8w4+bBNIDwbGU96f6HdamQJ/aCPlHN+840wPg=
