name: twilio
version: 0.0.1
basePath: "/2010-04-01"
credentials:
    - name: user_login
      existence: multiple
      creation: manual
      schema:
        "$ref": "./schema/user_login.json"
      permissions: "*"
    - name: api_key
      existence: multiple
      schema:
        "$ref": "./schema/api_key.json"
      creation: generated
      methods:
        - type: create
          input: master_credentials
          output: api_key
          src: "./create.js"
      permissions: "*"

default:
    provided:
        master_credentials:
            type: user_login
            description: "Credentials for your master twilio account"
    environments:
        - name: development
          credential: api_key
          permissions: "*"
          sharing: unique
