name: stripe
description: "Public production instance of Stripe"
type: subscription
locations:
  - name: api
    url: "https://api.stripe.com"

descriptors:
    default: 0.0.1
    supported:
        - version: 0.0.1
          src: "../../descriptors/stripe/service.yml"
