name: sendgrid
version: 0.0.1
basePath: "/v3"
credentials:
    - name: user_login
      existence: multiple
      creation: manual
      schema: "file://$DESCRIPTOR_HOME/schema/user_login.json"
      permissions: "*"
    - name: api_key
      existence: multiple
      schema: "file://$DESCRIPTOR_HOME/schema/api_key.json"
      creation: generated
      methods:
        - type: create
          input: master_credentials
          output: api_key
          src: "file://$DESCRIPTOR_HOME/create.js"
      permissions:
        - "mail.send"
        - "alerts.create"
        - "alerts.read"

default:
    provided:
        master_credentials:
            type: user_login
            description: "Credentials for your master sendgrid account"
    environments:
        - name: development
          credential: api_key
          permission: "*"
          sharing: unique
