name: sendgrid
version: 0.0.1
basePath: "/api/v1"
credentials:
    - name: user_login
      existence: multiple
      creation: manual
      schema: "file://$DESCRIPTOR_HOME/schema/user_login.json"
      permissions: "*"
    - name: api_key
      existence: multiple
      creation: generated
      schema: "file://$DESCRIPTOR_HOME/schema/api_key.json"
      permissions:
        - "mail.send"
        - "alerts.create"
        - "alerts.read"

default:
    provided:
        - type: user_login
          description: "Credentials for your master sendgrid account"
    environments:
        - name: production
          credential: api_key
          permissions: "*"
          sharing: unique
        - name: development
          credential: api_key
          permission: "*"
          sharing: unique
