name: sendgrid
description: "Production Instance of Sendgrid"
type: subscription
locations:
    api: "https://api.sendgrid.com"
    www: "https://www.sendgrid.com"

descriptors:
    default: 0.0.1
    supported:
        - name: 0.0.1
          url: "file://$ARIGATO_INSTALL/descriptors/sendgrid/service.yml"
