name: rollbar
description: "Production Instance of Rollbar"
type: subscription
locations:
  - name: api
    url: "https://api.rollbar.com"

descriptors:
    default: 0.0.1
    supported:
        - version: 0.0.1
          src: "../../descriptors/rollbar/service.yml"
